# Generated by Django 2.0.6 on 2019-02-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('realName', models.CharField(max_length=200)),
                ('accountNumber', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
