# Generated by Django 2.0.6 on 2019-02-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwApp', '0002_auto_20190220_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(default='', max_length=200),
        ),
    ]
